version: '3.8'

services:

    first-api:
        image: easy-http-server
        hostname: first
        deploy: 
            resources:
                limits: 
                    memory: 50M
        ports: 
            - "111:80"
        environment: 
            - HTTP_SERVER_URLS=http://first,http://second,http://third,http://fourth
                
    second-api:
        image: easy-http-server
        hostname: second
        deploy:
            resources:
                limits: 
                    memory: 50M
        ports: 
            - "112:80"
        environment: 
            - HTTP_SERVER_URLS=http://first,http://second,http://third,http://fourth
            
    third-api:
        image: easy-http-server
        hostname: third
        command: -a
        deploy:
            resources:
                limits: 
                    memory: 50M
        ports: 
            - "113:80"
        environment: 
            - HTTP_SERVER_URLS=http://first,http://second,http://third,http://fourth

    fourth-api:
        image: easy-http-server
        hostname: fourth
        command: -a --repeat-urls
        deploy:
            resources:
                limits: 
                    memory: 50M
        ports: 
            - "114:80"  
        environment: 
            - HTTP_SERVER_URLS=http://first,http://second,http://third,http://fourth